[api]
host = "0.0.0.0"
port = 8000
debug = true

[postgres_db]
host = "localhost"
port = 5432
database = "postgres_db"
user = "admin"
password = "admin"
echo = true

[telegram]
TELEGRAM_API_KEY = "5511764565:AAEKLFWxhsVmvsW692-I6FHT8xx9ZS_G4uo"
TELEGRAM_WEBHOOK_HOST = "https://43cc-85-195-102-78.ngrok-free.app"
TELEGRAM_WEBHOOK_PATH = "/webhooks/telegram"
